#+title: La conversion génique vers GC : processus majeur d'évolution des génomes 
#+latex_class: rapport
#+todo: TODO ->>- -REV | SENT DONE
#+latex_header: \input{header.tex}
#+OPTIONS: toc:nil todo:nil title:nil

\input{frontmatter.tex}

* Introduction

La recombinaison homologue est un processus majeur d'évolution des génomes.
C'est un processus très conservé, des procaryotes aux eucaryotes. C'est le
processus clé de réparation des lésions de l'ADN. Elles sont réparées sur la
base d'une matrice d'ADN homologue, donnant lieu à la formation transitoire d'un
/hétéroduplex/. Un hétéroduplex est un appariement entre deux brins homologues,
qui ne sont pas nécessairement rigoureusement complémentaires. Chez les
eucaryotes, la matrice est typiquement la région homologue correspondante, sur
le chromosome sœur. Les crossing-over méiotiques sont générés sous contrôle
génétique et impliquent une étape obligatoire de recombinaison. Chez les
procaryotes, cette matrice peut être acquise par transfert horizontal. La
recombinaison est le moyen principal de transfert de gène entre les bactéries.

Au voisinage de la région lésée --- puis réparée --- , des échanges
d'information génétique de petite échelle existent. Ils sont dûs à la correction
des erreurs d'appariement dans l'hétéroduplex. Ce sont des événements de
/conversion génique/. Ils donnent lieu à des transmissions non-mendéliennes
d'allèles : l'information génétique est transmise d'un brin vers l'autre, de
façon unidirectionnelle. Cette conversion est /biaisée/ dès lors que l'un des
allèles a une plus forte probabilité de transmission, à l'échelle de la
population. De nombreuses observations existent chez les eucaryotes ---
notamment chez la Levure et l'Homme --- , qui montrent que la conversion est
biaisée vers G ou C. Les allèles G ou C sont plus souvent transmis que les
allèles A ou T. Ce biais de conversion génique en faveur de GC --- \ac{gbgc} ---
a un impact fort sur l'évolution des génomes : il conditionne la structuration
en contenu GC des génomes ; il peut interférer avec la sélection naturelle ; et,
d'un point de vue pratique, il peut brouiller les tests de sélection naturelle.
Dans les régions fortement recombinantes, le contenu en GC est anormalement
élevé, lorsque le biais est observé. Le biais peut permettre de fixer des
mutations délétères, si celles-ci sont portées par les allèles G ou C du gène.
Enfin, l'action du biais laisse des traces génomiques équivalentes à celles de
la sélection naturelle : les tests classiques de détection confondent l'action
de la sélection avec celle du \ac{gbgc}.

Récemment, l'hypothèse du biais vers GC s'est étendue aux procaryotes. Des
observations montrent que les régions fortement recombinantes ont un contenu en
GC significativement plus élevé. L'extension de cette hypothèse aux procaryotes
pourrait permettre d'expliquer l'évolution du contenu en GC des populations
bactériennes. Nous verrons donc, dans une première partie, ce qu'est la
conversion génique biaisée ; dans une deuxième, les mécanismes qui la
sous-tendent ; dans une troisième, ses conséquences évolutives ; et dans une
dernière, les hypothèses permettant d'expliquer son existence.
 

* TODO Qu'est-ce que la conversion génique ? 

La conversion génique est un mécanisme qui intervient au cours de la réparation
de l'ADN. Lors d'une cassure double brin --- \ac{dsb} --- , la lésion est réparée par
recombinaison homologue. Les mésappariemments induits peuvent être corrigés,
donnant lieu à une transmission d'allèle non-mendélienne \cite{chen_mechanism_2008}. 

** ->>- La recombinaison homologue

La recombinaison homologue est un mécanisme ubiquitaire. Son fonctionnement est
très conservé à la fois chez les eucaryotes et chez les procaryotes. C'est le
mécanisme essentiel de /réparation/ de l'ADN. Il corrige les cassures
double-brins et les erreurs de fourches de réplications
\cite{lusetti_bacterial_2002}.

C'est la fonction principale et /première/ de la machinerie de recombinaison
homologue. Cependant, les mécanismes en jeu sont le lieu d'un brassage
génétique, aussi bien lors de la méiose eucaryote que lors des transferts de
gène procaryotes\cite{redfield_bacteria_2001}.  

\newthought{Ce brassage génétique} permet le ré-arrangement des combinaisons
d'allèles entre eux dans le pool génique. 

C'est un processus de brassage génétique clé. Chez les eucaryotes, la méiose
implique une étape de recombinaison, sous contrôle génétique strict
\cite{webster_direct_2012}. Chez les procaryotes, c'est le moteur des transferts
horizontaux de gènes \cite{didelot_impact_2010}.

\newthought{La séléction} naturelle est rendue plus efficace par la
recombinaison. En l'absence de recombinaison, les locus sous sélection
interfèrent entre eux. Ce sont les interférences de Hill et Robertson
\cite{hill_effect_1966}.

** TODO La conversion génique
** TODO La conversion génique biaisée vers GC
* TODO Comment ça marche ?
* TODO Quelles en sont les conséquences ?
* TODO Quelles hypothèses pour l'expliquer ?
* TODO Conclusion

\input{endmatter.tex}
