#+title: La conversion génique vers GC : processus majeur d'évolution des génomes 
#+latex_class: rapport
#+todo: TODO ->>- -REV | SENT DONE
#+latex_header: \input{header.tex}
#+OPTIONS: toc:nil todo:nil title:nil
#+BIBLIOGRAPHY: references 

\input{frontmatter.tex}

* Introduction
:PROPERTIES:
:UNNUMBERED: t
:END:

La recombinaison homologue est un processus majeur d'évolution des génomes.
C'est un processus très conservé, des procaryotes aux
eucaryotes\cite{cromie_recombination_2001}. C'est le processus clé de réparation
des lésions de l'ADN. Elles sont réparées sur la base d'une matrice d'ADN
homologue, donnant lieu à la formation transitoire d'un /hétéroduplex/. Un
hétéroduplex est un appariement entre deux brins homologues, qui ne sont pas
nécessairement rigoureusement complémentaires. Chez les eucaryotes, la matrice
est typiquement la région homologue correspondante, sur la chromatide sœur. Les
crossover méiotiques sont générés sous contrôle génétique et impliquent une
étape obligatoire de recombinaison\cite{mancera_high-resolution_2008}. Chez les
procaryotes, cette matrice peut être acquise par transfert horizontal. La
recombinaison est le moyen principal de transfert de gène entre procaryotes
\cite{vos_rates_2015}.

\newthought{Au voisinage} de la région lésée --- puis réparée --- , des échanges
d'information génétique de petite échelle existent\cite{duret_biased_2009}. Ils
sont dûs à la correction des erreurs d'appariement dans l'hétéroduplex. Ce sont
des événements de /conversion génique/. Ils donnent lieu à des transmissions
non-mendéliennes d'allèles : l'information génétique est transmise d'un brin
vers l'autre, de façon unidirectionnelle. Cette conversion est /biaisée/ dès
lors que l'un des allèles a une plus forte probabilité de transmission, à
l'échelle de la population. Chez les eucaryotes, de nombreuses observations
montrent que la conversion est biaisée /vers les bases G ou C/
\cite{pessia_evidence_2012, mancera_high-resolution_2008, duret_impact_2008}.
Les allèles G ou C sont plus souvent transmis que les allèles A ou T. Ce biais
de conversion génique en faveur de GC --- \ac{gbgc} --- a un impact fort sur
l'évolution des génomes : il conditionne la /structuration/ en contenu GC des
génomes\cite{duret_impact_2008} ; il /interfère/ avec la sélection
naturelle\cite{galtier_gc-biased_2009} ; et, d'un point de vue pratique, il
/brouille les tests/ de sélection naturelle\cite{ratnakumar_detecting_2010}.

Dans les régions fortement recombinantes, le contenu en GC est anormalement
élevé, lorsque le biais est observé\cite{duret_impact_2008}. Ce mécanisme permet
d'expliquer en partie les variations du contenu en GC, au sein d'un génome et
entre génomes. L'explication de ces variations suscite un débat entre les
partisans des hypothèses adaptatives, et ceux des hypothèses neutres. Les
hypothèses /adaptatives/ veulent que le contenu en GC soit un trait
sélectionné : il contribue en soi à la valeur adaptative de l'individu
\cite{hildebrand_evidence_2010}. Les hypothèses /neutres/ avancent qu'il est
également déterminé par des processus de dérive génétique et de mutation. Le
\ac{gbgc} est un autre processus neutre contribuant à déterminer le taux de GC.
En fait, c'est la contribution /relative/ des trois processus à la détermination
du taux de GC qui fait débat.

Le biais peut également permettre de fixer des mutations délétères, si celles-ci
sont portées par les allèles G ou C du gène. Il contrecarre l'action de la
sélection naturelle\cite{galtier_gc-biased_2009, galtier_adaptation_2007}.
Enfin, l'action du biais laisse des traces génomiques équivalentes à celles de
la sélection naturelle : les tests classiques de détection confondent l'action
de la sélection avec celle du \ac{gbgc}\cite{ratnakumar_detecting_2010}.

\newthought{Récemment,} l'hypothèse du biais vers GC s'est étendue aux
procaryotes\cite{lassalle_gc-content_2015}. Des observations montrent que les
régions fortement recombinantes ont un contenu en GC significativement plus
élevé. L'extension de cette hypothèse aux procaryotes représente une avancée
majeure : elle pourrait permettre d'expliquer l'évolution du contenu en GC des
populations bactériennes.

Nous verrons donc ce qu'est la conversion génique biaisée et les mécanismes qui
la sous-tendent, dans une première partie; dans une deuxième, les hypothèses
permettant d'expliquer son existence ; et dans une dernière, ses conséquences
évolutives.

* Qu'est-ce que la conversion génique ? 

La conversion génique est un mécanisme qui intervient au cours de la réparation
de l'ADN. Lors d'une cassure double brin --- \ac{dsb}, Double Strand Break --- ,
la lésion est réparée par recombinaison homologue. Les mésappariements induits
peuvent être corrigés, donnant lieu à une transmission d'allèle non-réciproque
\cite{chen_mechanism_2008}.

#+name: image_1
#+BEGIN_LaTeX
\addfig{%
  \centering
  \includegraphics[width=\linewidth]{img/conversion.pdf}
  \caption{\textbf{Recombinaison homologue} 
  }
  \label{recombinaison}
}

#+END_LaTeX

** Recombinaison homologue

La réplication de l'ADN est une étape clé du cycle cellulaire. Elle implique la
formation de fourches de réplications. Les lésions subies par l'ADN en cours de
réplication empêchent le déplacement de ces fourches, et notamment les cassures
double brins. Ces \ac{dsb} sont extrêmement cytotoxiques : ils causent l'arrêt
de la réplication, la perte de chromosomes, sont mutagènes et conduisent à la
mort cellulaire \cite{watson_molecular_2014}. La bonne conduite de la
réplication nécessite de réparer ces cassures, de façon non-mutagène. La
recombinaison homologue est le moyen préférentiel de réparation
\cite{lusetti_bacterial_2002}. Compte tenu de son importance dans le cycle
cellulaire, les mécanismes qui la sous-tendent sont ubiquitaires et extrêmement
conservés, des phages aux mammifères \cite{cromie_recombination_2001}.

*** Mécanismes de recombinaison homologue

La recombinaison se déroule en plusieurs étapes. 

Les cassures doubles brins --- \ac{dsb} --- sont générées par des processus
mutagènes ou sous contrôle génétique, notamment lors de la méiose. Après la
formation des \ac{dsb}, les extrémités $5'$ de la lésion subissent une
/résection/, délétion locale d'une section d'ADN. Chez /E.coli/, le complexe
RecBCD est responsable de cette digestion. Il a une activité d'hélicase : il
dissocie les deux brins d'ADN ; et de nucléase : il digère localement les brins
dissociés \cite{dillingham_recbcd_2008}.

Le brin à l'extrémité $3'$ /envahit/ les brins complémentaires de la molécule
intacte. Ce brin recherche ensuite activement les zones d'homologie. Lorsqu'une
zone est déterminée, les brins sont échangés. L'ensemble de ce processus est
catalysé par la nucléo-protéine RecA \cite{chen_mechanism_2008} ou ses
homologues. C'est l'acteur moléculaire clé de la recombinaison homologue.

L'échange des brins entraîne la formation d'un hétéroduplex. L'intégrité de
l'hétéroduplex est maintenue par une structure appelée /jonction de Holliday/.
Des mésappariements peuvent exister entre les brins de l'hétéroduplex : deux
brins homologues ne sont pas systématiquement complémentaires. Leur correction
peut donner lieu à une conversion génique (voir [[#conversion]]).

La zone de résection est ensuite comblée par la /synthèse/ d'ADN en utilisant le
brin homologue comme matrice. Enfin, les intermédiaires de recombinaisons sont
/résolus/ par des résolvases qui clivent les jonctions de Holliday. La résolution
des intermédiaires de recombinaisons peut donner des produits dits crossovers ou
non-crossovers, entraînant respectivement l'échange des régions flanquantes ou
non \cite{mancera_high-resolution_2008}.

#+BEGIN_LaTeX
\begin{transition}
La réparation des cassures est la fonction principale et \emph{première} de la
machinerie de recombinaison homologue. Cependant, les mécanismes en jeu sont le
lieu d'un brassage génétique, aussi bien lors de la méiose eucaryote que lors
des transferts de gène procaryotes \cite{redfield_bacteria_2001}.
\end{transition}
#+END_LaTeX

*** La recombinaison méiotique : étape clé de la méiose

Chez les eucaryotes, la méiose implique la formation de DSB sous contrôle
génétique rigoureux, qui sont réparés par recombinaison homologue
\cite{chapman_playing_2012}. Les enzymes Spo11 introduisent aléatoirement des
\ac{dsb}. Cependant, la distribution des sites de coupure est variable : il
existe des /hotspots/ de cassure, et donc de recombinaison. Par opposition, les
/coldspots/ sont des régions moins soumises que d'autres aux cassures.

La réparation de ces \ac{dsb} par recombinaison homologue est requise pour
l'appariement et la ségrégation des chromosomes homologues au cours de la
méiose. Selon le mode de clivage des jonctions de Holliday par les résolvases,
des crossovers se forment entre les chromosomes parentaux. 

Ces crossovers entraînent le brassage des allèles, un processus bénéfique sur le
plan évolutif\cite{webster_direct_2012}. En effet, il casse les liaisons entre
allèles : la sélection élimine alors plus efficacement les variants délétères et
promeut les variants bénéfiques \cite{otto_resolving_2002}. C'est l'une des
hypothèses permettant d'expliquer l'évolution de la reproduction
sexuée\cite{otto_why_2006}.

*** La recombinaison comme moteur des transferts horizontaux de gènes

Étant donné la taille des populations bactériennes et les temps évolutifs en
jeu, la recombinaison a un impact majeur sur l'évolution procaryote
\cite{didelot_impact_2010}. C'est le moteur des transferts de gène. Ceux-ci sont
médiés soit par des vecteurs, les plasmides ou les phages, soit par un état de
compétence naturelle, /via/ l'acquisition passive ou active d'ADN exogène. 

La principale fonction de la recombinaison /homologue/ semble être la réparation
des lésions de l'ADN \cite{fall_horizontal_2007, michod_adaptive_2008}. 

Il est difficile d'estimer les fréquences de recombinaison procaryotes. Elles
sont très variables, au sein d'une espèce, d'un écotype ou entre espèces
\cite{didelot_impact_2010}.

\todo{Revoir cette partie}

#+BEGIN_LaTeX
\begin{transition}
Après la résolution des intermédiaires de recombinaison, des mésappariements
peuvent exister entre les différents brins. Leur correction entraîne une
conversion génique.
\end{transition}
#+END_LaTeX

#+name: image_2
#+BEGIN_LaTeX
\addfig{%
  \centering
  \includegraphics[width=\linewidth]{img/mutslh.pdf}
  \caption{\textbf{Correction des mésappariements par MutSLH}}
  \label{mutslh}
}
#+END_LaTeX

** Conversion génique
:PROPERTIES:
:CUSTOM_ID: conversion
:END:

La conversion génique est l'échange non réciproque d'information génétique.
C'est une transmission non-mendélienne : l'un des allèles a une plus forte
probabilité d'être transmis que l'autre\cite{chen_gene_2007}. 

Considérons le cas de la transmission de l'allèle $A$ et de son homologue $a$,
au cours de la méiose. Après la méiose, le génotype attendu est $AAaa$.
Cependant, un évènement de conversion de gène peut conduire à des génotypes de
type $Aaaa$ ou $AAAa$. 

Au cours de la réparation des DSB, la conversion peut subvenir de deux façons.
i) L'allèle $A$ est proche du site d'initiation de la cassure. Il fait partie de
la résection, l'allèle $a$ est copié vers le brin réparé. $Aaaa$ est le génotype
obtenu. ii) L'intermédiaire de recombinaison présente un polymorphisme $Aa$ sur
l'un des hétéroduplex. La machinerie de réparation des mésappariements ---
\ac{mmr} --- les prend en charge. $a$ est alors converti en $A$, ou
réciproquement.

Chez /E.coli/, la détection des mésappariements est effectuée par les dimères
des enzymes MutS. Les mésappariements sont reconnus par la distorsion qu'ils
causent à la structure de l'ADN. Les enzymes MutL et MutH sont alors recrutées.
Une cassure est introduite dans l'un des brins, suivie par une résection souvent
supérieure à $1$kb à proximité de la cassure. Une ADN polymérase utilise ensuite
le brin intact pour synthétiser la région complémentaire. Les eucaryotes
possèdent des protéines aux fonctions homologues, appelées respectivement MSH et
MLH pour /MutS Homologs/ et /MutL Homologs/. Ce sont des composants de la voie
\ac{ner}, /Nucleotide Excision Repair/.

Au cours de la recombinaison, le système de \ac{mmr} est la voie préférentielle
de correction des mésappariements dans l'hétéroduplex. Néanmoins, la voie
\ac{ber}, /Base Excision Repair/, est une alternative à ce système.

Elle entraîne l'excision de l'une des bases du mésappariement, puis son
remplacement par la base complémentaire à l'autre. Les ADN glycosylases excisent
les bases avec une spécificité de substrat : chaque base $A$, $T$, $C$ ou $G$ a
une ADN glycosylase correspondante et spécifique.

Dans tous les cas, le génotype de la région --- ou de la base --- digérée est
/converti/ par celui du brin intact. Le transfert a lieu entre séquences
homologues, qu'elles soient sur des chromatides sœurs, sur le même chromosome ou
sur des chromosomes différents \cite{chen_gene_2007}.

#+BEGIN_LaTeX
\begin{transition}

En théorie, la conversion $a \mapsto A$ a lieu avec la même fréquence que celle
de la conversion $A \mapsto a$. Cependant, dès lors qu'un allèle est plus
souvent converti que l'autre, à l'échelle de la population, la conversion
génique est {\em biaisée}. Chez les eucaryotes, de nombreuses observations montrent
que les mésappariements $GA$, $GT$, $CA$ ou $CT$ sont plus fréquemment corrigés
en $GC$ qu'en $AT$ \cite{duret_biased_2009}. 

\end{transition}
#+END_LaTeX

** La conversion génique biaisée vers GC

\todo{premiers articles gbgc marais et duret 2003 et 2001 etc}

Mancera /et al/ \cite{mancera_high-resolution_2008} ont génotypé l'ensemble des
quatre haplotypes --- les tétrades --- résultants des produits de méiose de 46
levures, à haute résolution. Ils montrent qu'1% du génome de chaque produit de
méiose est soumis à de la conversion génique. Ces régions montrent une
transmission biaisée en faveur des allèles G ou C. Ils sont transmis avec une
probabilité 1.3% plus élevée qu'attendu sous l'hypothèse d'une transmission
mendélienne \cite{mancera_high-resolution_2008}. 

Chez la levure, le \ac{gbgc} est associé spécifiquement aux produits de
recombinaisons entraînant des crossovers \cite{lesecque_gc-biased_2013}. Il est
également associé aux évènements de conversion /simple/ --- par opposition aux
évènements complexes. Lors d'un évènement de conversion simple, le même brin est
le donneur de la conversion sur l'ensemble de la région convertie. Lors d'un
évènement complexe, les deux brins de l'hétéroduplex peuvent être donneur. 

#+BEGIN_LaTeX
\begin{transition}
  Les causes moléculaires de l'existence d'un tel mécanisme suscitent beaucoup
  d'interrogations. Différentes hypothèses ont été avancées : elles font l'objet
  de la partie suivante. 
\end{transition}
#+END_LaTeX

* Quelles hypothèses pour l'expliquer ?
** Des propriétés inhérentes à la machinerie de réparation ?
La machinerie de réparation pourrait dans sa structure présenter un biais en
faveur de la transmission des allèles G ou C au cours de la conversion génique. 
** Un processus sélectionné pour compenser la mutation ?
La mutation est universellement biaisée vers AT
\cite{lynch_rate_2010,hershberg_evidence_2010}. Le \ac{gbgc} pourrait avoir été
sélectionné pour contrecarrer les effets de ce biais mutationne
\cite{marais_biased_2003}. Des preuves théoriques et expérimentales existent
pour soutenir cette hypothèse.

La voie \ac{ber} implique des DNA glycosylases spécifiques. Chez les mammifères,
il existe des Thymines DNA glycosylases, qui excisent spécifiquement les thymines. 

* Quelles en sont les conséquences ?
  Puisqu'elle augmente la probabilité de fixation des allèles G ou C, la
  conversion biaisée joue un rôle important dans la structuration du contenu en
  GC des génomes. La conversion biaisée n'est pas en soi liée à la sélection
  naturelle. Elle affecte cependant la fixation d'allèles d'une façon similaire
  à la sélection\cite{nagylaki_evolution_1983}. Elle a donc deux conséquences
  directes et indirectes : elle interfère avec la sélection et confond les tests
  de sélection naturelle.
** Structure le contenu en GC
Les bases C et G sont liées par trois liaisons hydrogènes : elles sont plus
stables que les liaisons doubles entre A et T. Certains pensent qu'en soi, le
taux de GC est un trait adaptatif : à l'échelle du génome, un contenu en GC
supérieur en augmenterait la stabilité. Ce modèle rencontre néanmoins de
nombreuses difficultés, chez les eucaryotes comme les procaryotes. La conversion
biaisée vers GC a été proposée comme modèle alternatif expliquant les variations
en taux de GC --- \ac{gc} --- , au sein d'un génome et entre génomes.

*** Le contenu GC des génomes mammifères et la théorie des isochores
Les mammifères montrent des variations intragénomiques de grande échelle en taux
de GC\cite{eyre-walker_evolution_2001} ( $>$ 100kb ). Ces régions relativement
homogènes en taux de GC ont été baptisées /isochores/. Leur origine fait débat :
est-ce un trait sélectionné ou une conséquence évolutive des patrons de
mutations ?

Le modèle sélectionniste se heurte au fait que les variations du GC affectent
les sites fonctionnels comme neutres. En fait, l'évolution des isochores résulte
de l'accumulation de mutations. Il faudrait donc un avantage sélectif
significatif à l'acquisition d'une mutation ponctuelle vers G ou C, dans un
isochore de plus de 100kb.

Le \ac{gbgc} a été proposé pour expliquer l'apparition et le maintien des isochores
riches en GC\cite{duret_new_2006}. Un argument fort de l'hypothèse \ac{gbgc} est que
les zones fortement recombinantes ont un \ac{gc} supérieur. C'est le cas chez
l'Homme\cite{duret_impact_2008, berglund_hotspots_2009}. L'apparition et la
disparition successive de points chauds de recombinaison explique la succession
des épisodes de \ac{gbgc} : il conditionne le contenu en GC local, permettant
d'expliquer la structuration des isochores riches en GC. 

La taille des chromosomes a un impact fort sur le \ac{gc} : le taux de
recombinaison à l'échelle de la Mb est fortement corrélé à la taille du
chromosome, chez le poulet et l'Homme\cite{kaback_chromosome_1999}. Autrement
dit, les grands chromosomes recombinent peu, les petits beaucoup. Comme attendu
sous l'hypothèse \ac{gbgc}, chez l'opossum, les petits chromosomes ont un taux
de GC plus élevé que les grands.

#+BEGIN_LaTeX
\begin{transition}
  Ainsi, chez les mammifères, le contenu en GC est déterminé par la
  recombinaison : elle augmente la probabilité de fixation des mutations vers
  GC. Elle a pour impact de structurer localemnt le \ac{gc} au gré des épisodes
  de points chauds de recombinaisons. De nombreuses preuves indirectes attestent
  de l'existence du \ac{gbgc} chez les eucaryotes. Qu'en est-il chez les
  procaryotes ?
\end{transition}
#+END_LaTeX

*** Un \ac{gbgc} procaryote ?
Le taux moyen de GC --- \ac{gc} --- chez les procaryotes est extrêmement
diversifié : il varie de 14 à 75% selon les
espèces\cite{mccutcheon_functional_2010}. Certains y voient une adaptation aux
conditions environnementales. En effet, la température de croissance optimale
est corrélée avec le taux de GC par exemple. Cependant, ces effets
environnementaux sont faibles, et les pressions de sélection associées
mystérieuses. Le modèle classique considère que le \ac{gc} est essentiellement
déterminé par la mutation, qui est biaisée vers
AT\cite{hershberg_evidence_2010,sueoka_directional_1988}.

Récemment, il a été démontré que les gènes recombinants ont un taux de GC
supérieur aux non-recombinants\cite{lassalle_gc-content_2015}, chez 21 espèces
bactériennes. La troisième position des codons est d'autant plus affectée
qu'elle est moins soumise à la sélection. Le code génétique étant redondant, une fs
mutation en troisième position ne change pas nécessairement l'acide aminé : la
mutation est synonyme. L'excès de substitutions AT $\rightarrow$ GC peut être dû
à la pression de sélection sur les autres positions, qui tend à conserver la
fonction de la protéine. Les régions intergéniques flanquantes des gènes
recombinants ont également un \ac{gc} supérieur à celles des régions flanquantes
des gènes non-recombinants. C'est un patron attendu sous l'hypothèse \ac{gbgc}.
Cette corrélation entre taux de recombinaison et contenu en GC est similaire
quantitativement à celle observée chez l'Humain\cite{lassalle_gc-content_2015}.

#+BEGIN_LaTeX
\begin{transition}
  Le \ac{gbgc} explique donc en partie la structuration en GC des génomes
  mammifères, eucaryotes et probablement procaryote. Il augmente la probabilité
  de fixation des allèles G ou C : il peut même s'opposer à la sélection
  naturelle si cette fixation est faiblement délétère.  
\end{transition}
#+END_LaTeX
  
#+BEGIN_LaTeX
\addfig{%
  \centering
  \missingfigure
  \caption{\textbf{Pollard figure har1} 
  }
  \label{pollard}
}

#+END_LaTeX

** Interfère avec la sélection 
La conversion génique affecte la probabilité de fixation d'un allèle de façon
similaire à la sélection \cite{nagylaki_evolution_1983}.

Si un allèle faiblement délétère est porté par une substitution AT $\rightarrow$
GC, le \ac{gbgc} peut entraîner sa fixation dans la population. À l'inverse, il
peut empêcher la fixation d'une mutation GC $\rightarrow$ AT. Il contrecarre les
effets de la sélection naturelle.

Galtier et collaborateurs ont analysé la séquence des protéines de primates qui
montrent un taux d'évolution plus rapide depuis la divergence avec les macaques
\cite{galtier_gc-biased_2009}. Cette accélération de la vitesse de substitution
dans les séquences codantes peut /a priori/ être due à un changement de fonction
/adaptatif/. Cependant, les séquences analysées montrent un excès significatif
de mutations AT $\rightarrow$ GC. De plus, ces mutations sont significativement
plus souvent non-synonymes : elles changent l'acide aminé.

En clair, des régions auparavant conservées ont subie un ou plusieurs épisodes
de gBGC, qui a entraîné deux choses : i) le \ac{gc} local a augmenté, et ii) la
fonction des régions a changé.[fn:1: Voir également figure \ref{pollard}.]

Pollard et collaborateurs ont également analysé les régions non-codantes
accélérées uniquement dans la lignée humaine : les \ac{har}, Human Accelerated
Regions.

** Brouille les tests de sélection 
Les tests de sélection reposent classiquement sur deux principes généraux
\cite{hurst_genetics_2009} : ce qui évolue lentement est fonctionnel, ce qui
évolue vite est adaptatif. 
* Conclusion
:PROPERTIES:
:UNNUMBERED: t
:END:

\input{endmatter.tex}
