#+title: La conversion génique vers GC : processus majeur d'évolution des génomes 
#+latex_class: rapport
#+todo: TODO ->>- -REV | SENT DONE
#+latex_header: \input{header.tex}
#+OPTIONS: toc:nil todo:nil title:nil
#+BIBLIOGRAPHY: references 

\input{frontmatter.tex}

* Introduction
:PROPERTIES:
:UNNUMBERED: t
:END:

#+name: holliday
#+BEGIN_LaTeX
\addfig{%
  \centering
  \includegraphics[width=\linewidth]{img/holliday.png}
  \caption{\textbf{Le modèle classique de formation d'un hétéroduplex par
      invasion de brin.} \rmfamily%
    \setstretch{1.1} %
    Après la formation d'une cassure double brin en \texttt{a}, les extrémités
    $3'$ sont exposées par résection, en \texttt{b}. Le premier brin
    \crule[LightGray]{0.5cm}{0.15cm} porteur de l'allèle B envahit le brin
    \crule[Cyan]{0.5cm}{0.15cm} porteur de l'allèle b, formant une jonction de Holliday, en \texttt{c}.
    Localement, l'hétéroduplex ainsi formé montre des mésappariements, en
    \texttt{d}. \\
    {\em Adapté de Molecular Biology Of The Gene, Watson, 2012. } }
  \label{holliday}
}
#+END_LaTeX

La recombinaison homologue est un processus majeur d'évolution des génomes.
C'est un processus très conservé, des procaryotes aux
eucaryotes\cite{cromie_recombination_2001}. C'est le mécanisme clé de réparation
des lésions de l'ADN. Elles sont réparées sur la base d'une matrice d'ADN
homologue, donnant lieu à la formation transitoire d'un /hétéroduplex/. Un
hétéroduplex est un appariement entre deux brins homologues, qui ne sont pas
nécessairement rigoureusement complémentaires. Chez les eucaryotes, la matrice
est typiquement la région homologue correspondante, sur la chromatide sœur. Les
crossover méiotiques sont générés sous contrôle génétique et impliquent une
étape obligatoire de recombinaison\cite{mancera_high-resolution_2008}. Chez les
procaryotes, cette matrice peut être acquise par transfert horizontal. La
recombinaison est le moyen principal de transfert de gène entre procaryotes.

\newthought{Au voisinage} de la région lésée --- puis réparée --- , des échanges
d'information génétique de petite échelle existent\cite{duret_biased_2009}. Ils
sont dûs à la correction des erreurs d'appariement dans l'hétéroduplex. Ce sont
des événements de /conversion génique/. Ils donnent lieu à des transmissions
non-mendéliennes d'allèles : l'information génétique est transmise d'un brin
vers l'autre, de façon unidirectionnelle. Cette conversion est /biaisée/ dès
lors que l'un des allèles a une plus forte probabilité de transmission, à
l'échelle de la population. Chez les eucaryotes, de nombreuses observations
montrent que la conversion est biaisée /vers les bases G ou C/
\cite{pessia_evidence_2012, mancera_high-resolution_2008, duret_impact_2008}.
Les allèles G ou C sont plus souvent transmis que les allèles A ou T. Ce biais
de conversion génique en faveur de GC --- \ac{gbgc} --- a un impact fort sur
l'évolution des génomes : il conditionne la /structuration/ en contenu GC des
génomes\cite{duret_impact_2008} ; il /interfère/ avec la sélection
naturelle\cite{galtier_gc-biased_2009} ; et, d'un point de vue pratique, il
/brouille les tests/ de sélection naturelle\cite{ratnakumar_detecting_2010}.

Dans les régions fortement recombinantes, le contenu en GC est anormalement
élevé, lorsque le biais est observé\cite{duret_impact_2008}. Ce mécanisme permet
d'expliquer en partie les variations du contenu en GC, au sein d'un génome et
entre génomes. L'explication de ces variations suscite un débat entre les
partisans des hypothèses adaptatives, et ceux des hypothèses neutres. Les
premiers veulent que le contenu en GC soit un trait sélectionné : il contribue
en soi à la valeur adaptative de l'individu \cite{hildebrand_evidence_2010}. Les
seconds avancent qu'il est également déterminé par des processus de dérive
génétique et de mutation. Le \ac{gbgc} est un autre processus neutre contribuant
à déterminer le taux de GC --- \ac{gc}. En fait, c'est la contribution
/relative/ des trois processus à la détermination du taux de GC qui fait débat.

Le biais peut également permettre de fixer des mutations délétères, si celles-ci
sont portées par les allèles G ou C du gène. Il contrecarre l'action de la
sélection naturelle\cite{galtier_gc-biased_2009, galtier_adaptation_2007}.
Enfin, l'action du biais laisse des traces génomiques équivalentes à celles de
la sélection naturelle : les tests classiques de détection confondent l'action
de la sélection avec celle du \ac{gbgc}\cite{ratnakumar_detecting_2010}.

\newthought{Récemment,} l'hypothèse du biais vers GC s'est étendue aux
procaryotes\cite{lassalle_gc-content_2015}. Des observations montrent que les
régions fortement recombinantes ont un contenu en GC significativement plus
élevé. L'extension de cette hypothèse aux procaryotes représente une avancée
majeure : elle pourrait permettre d'expliquer l'évolution du contenu en GC des
populations bactériennes.

Nous verrons donc ce qu'est la conversion génique biaisée et les mécanismes qui
la sous-tendent, dans une première partie; dans une deuxième, les hypothèses
permettant d'expliquer son existence ; et dans une dernière, ses conséquences
évolutives.

* Qu'est-ce que la conversion génique ? 

La conversion génique est un mécanisme qui intervient au cours de la réparation
de l'ADN. Lors d'une cassure double brin --- \ac{dsb}, Double Strand Break --- ,
la lésion est réparée par recombinaison homologue. Les mésappariements induits
peuvent être corrigés, donnant lieu à une transmission d'allèle non-réciproque
\cite{chen_mechanism_2008}.

#+name: recomb
#+BEGIN_LaTeX
\addfig{%
  \centering
  \includegraphics[scale=0.7]{img/conversion.png}
  \caption{\textbf{Le modèle classique de réparation des cassures doubles brins
      par recombinaison homologue} \rmfamily%
    \setstretch{1.1} %
    Les cassures doubles brins sont suivies d'une résection dans le sens $5'
    \rightarrow 3'$. L'un des brins ainsi exposé cherche ensuite activement une
    séquence homologue. Au cours de l'invasion de brin, une boucle D se forme,
    ainsi qu'une jonction de Holliday. La synthèse d'ADN a lieu en utilisant la
    séquence intacte comme matrice. La résolution de ces structures peut passer
    par différentes voies. En \texttt{b}, le brin réparé doit être apparié à la
    l'extrémité du brin originel : c'est la {\em second-end capture.} Selon le
    mode de clivage des résolvases, le produit obtenu est non-crossover ou
    crossover (\texttt{d}). Chez les eucaryotes, la {\em dissolution} est une
    autre voie de résolutions des doubles jonctions de Hollidays (\texttt{e}).
    En \texttt{c}, la voie \ac{sdsa}, Synthesis-Dependent Strand-Annealing,
    implique une étape de dénaturation, puis de ré-appariement du brin
    envahisseur avec l'autre extrémité $3'$ de la cassure. La synthèse se
    poursuit et est suivie d'une étape de ligation. Dans tous les cas, des
    hétéroduplex sont formés, dès lors que les séquences
    appariées ne sont pas rigoureusement identiques. \\
    {\em Tiré de Chen {\em et al.}, 2007\cite{chen_gene_2007}.} }
  \label{recombinaison}
}
#+END_LaTeX

** Recombinaison homologue

La réplication de l'ADN est une étape clé du cycle cellulaire. Elle implique la
formation de fourches de réplications. Les lésions subies par l'ADN en cours de
réplication empêchent le déplacement de ces fourches, et notamment les cassures
double brins. Ces cassures sont extrêmement cytotoxiques : elles causent l'arrêt
de la réplication, la perte de chromosomes, sont mutagènes et conduisent à la
mort cellulaire. La bonne conduite de la réplication nécessite de réparer ces
cassures, de façon non-mutagène. La recombinaison homologue est le moyen
préférentiel de réparation. Compte tenu de son importance dans le cycle
cellulaire, les mécanismes qui la sous-tendent sont ubiquitaires et extrêmement
conservés, des phages aux mammifères \cite{cromie_recombination_2001}.

*** Mécanismes de recombinaison homologue

Les cassures doubles brins --- \ac{dsb} --- sont générées par des agents
mutagènes ou sous contrôle génétique, notamment lors de la méiose. Après la
formation des \ac{dsb}, les extrémités $5'$ de la lésion subissent une
/résection/, délétion locale d'une section d'ADN. Chez /E.coli/, le complexe
RecBCD est responsable de cette digestion. Il a une activité d'hélicase : il
dissocie les deux brins d'ADN ; et de nucléase : il digère localement les brins
dissociés \cite{dillingham_recbcd_2008}.

Le brin à l'extrémité $3'$ /envahit/ les brins complémentaires de la molécule
intacte. Ce brin recherche ensuite activement les zones d'homologie. Lorsqu'une
zone est déterminée, les brins sont échangés. L'ensemble de ce processus est
catalysé par la nucléo-protéine RecA \cite{chen_mechanism_2008} ou ses
homologues. C'est l'acteur moléculaire clé de la recombinaison homologue.

L'échange des brins entraîne la formation d'un hétéroduplex[fn:1:Voir figure
\ref{holliday}]. L'intégrité de l'hétéroduplex est maintenue par une structure
appelée /jonction de Holliday/. Des mésappariements peuvent exister entre les
brins de l'hétéroduplex : deux brins homologues ne sont pas systématiquement
complémentaires. Leur correction peut donner lieu à une conversion génique.

La zone de résection est ensuite comblée par la /synthèse/ d'ADN en utilisant le
brin homologue comme matrice. Enfin, les intermédiaires de recombinaisons sont
/résolus/ par des résolvases qui clivent les jonctions de Holliday. La résolution
des intermédiaires de recombinaisons peut donner des produits dits crossovers ou
non-crossovers, entraînant respectivement l'échange des régions flanquantes ou
non \cite{mancera_high-resolution_2008}.

#+BEGIN_LaTeX
\begin{transition}
La réparation des cassures est la fonction principale et \emph{première} de la
machinerie de recombinaison homologue. Cependant, les mécanismes en jeu sont le
lieu d'un brassage génétique, aussi bien lors de la méiose eucaryote que lors
des transferts de gène procaryotes \cite{redfield_bacteria_2001}.
\end{transition}
#+END_LaTeX

*** La recombinaison méiotique : étape clé de la méiose

Chez les eucaryotes, la méiose implique la formation de DSB, par les enzymes
Spo11, sous contrôle génétique rigoureux. Ils sont réparés par recombinaison
homologue \cite{chapman_playing_2012}. Cependant, la distribution des sites de
coupure est variable : il existe des /hotspots/ de cassure, et donc de
recombinaison. Par opposition, les /coldspots/ sont des régions moins soumises
que d'autres aux cassures.

La réparation des \ac{dsb} par recombinaison homologue est requise pour
l'appariement et la ségrégation des chromosomes homologues au cours de la
méiose. Selon le mode de clivage des jonctions de Holliday par les résolvases,
des crossovers se forment entre les chromosomes parentaux. Ces crossovers
entraînent le brassage des allèles, un processus bénéfique sur le plan
évolutif\cite{webster_direct_2012}. En effet, il casse les liaisons entre
allèles : la sélection élimine alors plus efficacement les variants délétères et
promeut les variants bénéfiques \cite{otto_resolving_2002}.

*** La recombinaison chez les procaryotes

Étant donné la taille des populations bactériennes et les temps évolutifs en
jeu, la recombinaison a un impact majeur sur l'évolution procaryote
\cite{didelot_impact_2010}. C'est le moteur des transferts de gène. Ceux-ci sont
médiés soit par des vecteurs, les plasmides ou les phages, soit par un état de
compétence naturelle, /via/ l'acquisition passive ou active d'ADN exogène. La
principale fonction de la recombinaison /homologue/ semble être la réparation
des lésions de l'ADN \cite{fall_horizontal_2007}. L'acquisition de matériel
génétique exogène est un effet secondaire des mécanismes de réparation de l'ADN.
Cet effet secondaire est bénéfique sur le plan évolutif dès lors que le matériel
acquis apporte un avantage sélectif à l'individu[fn:2: ou s'il manipule le
comportement de reproduction de l'hôte en faveur de sa dissémination…].

#+BEGIN_LaTeX
\begin{transition}
Après la résolution des intermédiaires de recombinaison, des mésappariements
peuvent exister entre les différents brins. Leur correction entraîne une
conversion génique.
\end{transition}
#+END_LaTeX

#+name: mutslh 
#+BEGIN_LaTeX
\addfig{%
  \centering
  \includegraphics[scale = 1.2]{img/mutslh.png}
  \caption{\textbf{Correction des mésappariements par le complexe MutSLH} \rmfamily%
    \setstretch{1.1}%
    Le dimère de MutS reconnaît l'anomalie structurelle de l'ADN causé par un
    mésappariement. Il recrute alors l'enzyme MutL, qui à son tour recrute
    l'endonucléase MutH. Celle-ci introduit une cassure sur l'un des brins. Elle
    est suivie d'une résection par une exonucléase, puis par la synthèse
    \emph{via} une ADN polymérase, sur la base du brin intact.\\
    {\em Adapté de Molecular Biology of The Gene, Watson, 2012.}
  }
  \label{mutslh}
}
#+END_LaTeX

** Conversion génique
:PROPERTIES:
:CUSTOM_ID: conversion
:END:

La conversion génique est l'échange non réciproque d'information génétique.
C'est une transmission non-mendélienne : l'un des allèles a une plus forte
probabilité d'être transmis que l'autre\cite{chen_gene_2007}. 

Considérons le cas de la transmission de l'allèle $A$ et de son homologue $a$,
au cours de la méiose. Après la méiose, le génotype attendu est $AAaa$. Un
évènement de conversion de gène peut conduire à des génotypes de type $Aaaa$ ou
$AAAa$.

Au cours de la réparation des DSB, la conversion peut subvenir de deux façons.
i) L'allèle $A$ est proche du site d'initiation de la cassure. Il fait partie de
la résection, l'allèle $a$ est copié vers le brin réparé. $Aaaa$ est le génotype
obtenu. ii) L'intermédiaire de recombinaison présente un polymorphisme $Aa$ sur
l'un des hétéroduplex. La machinerie de réparation des mésappariements ---
\ac{mmr} --- les prend en charge. $a$ est alors converti en $A$, ou
réciproquement.

Chez /E.coli/, la détection des mésappariements est effectuée par les dimères
des enzymes MutS. Les mésappariements sont reconnus par la distorsion qu'ils
causent à la structure de l'ADN. Les enzymes MutL et MutH sont alors recrutées.
Une cassure est introduite dans l'un des brins, suivie par une résection souvent
supérieure à $1$ kb à proximité de la cassure. Une ADN polymérase utilise
ensuite le brin intact pour synthétiser la région complémentaire. Les eucaryotes
possèdent des protéines aux fonctions homologues, appelées respectivement MSH et
MLH pour /MutS Homologs/ et /MutL Homologs/. Ce sont des composants de la voie
\ac{ner}, /Nucleotide Excision Repair/.

Au cours de la recombinaison, le système de \ac{mmr} est la voie préférentielle
de correction des mésappariements dans l'hétéroduplex. Néanmoins, la voie
\ac{ber}, /Base Excision Repair/, est une alternative à ce système.

Elle entraîne l'excision de l'une des bases du mésappariement, puis son
remplacement par la base complémentaire à l'autre. Les ADN glycosylases excisent
les bases avec une spécificité de substrat : chaque base A, T, C ou G a une ADN
glycosylase correspondante et spécifique.

Dans tous les cas, le génotype de la région --- ou de la base --- digérée est
/converti/ par celui du brin intact. Le transfert a lieu entre séquences
homologues, qu'elles soient sur des chromatides sœurs, sur le même chromosome ou
sur des chromosomes différents \cite{chen_gene_2007}.

#+BEGIN_LaTeX
\begin{transition}
En théorie, la conversion $a \mapsto A$ a lieu avec la même fréquence que celle
de la conversion $A \mapsto a$. Cependant, dès lors qu'un allèle est plus
souvent converti que l'autre, à l'échelle de la population, la conversion
génique est {\em biaisée}. Chez les eucaryotes, de nombreuses observations montrent
que les mésappariements GA, GT, CA ou CT sont plus fréquemment corrigés
en GC qu'en AT \cite{duret_biased_2009}. 
\end{transition}
#+END_LaTeX

#+BEGIN_LaTeX
\addfig{% 
  \centering
  \includegraphics[width=0.5\linewidth]{img/cytosine.png}
  \caption{\textbf{La déamination spontanée des méthyl-cytosines.} \rmfamily
    \setstretch{1.1} La perte du groupement {\color{Red} amine} d'une cytosine
    méthylée génère une base naturelle de l'ADN : la thymine. Cette perte peut
    avoir lieu dans des conditions physiologiques normales. La réplication d'une
    telle erreur conduit à l'introduction d'un A sur le brin opposé, au lieu du
    G attendu. Le mécanisme de Base Excision Repair excise préférentiellement
    les thymines chez les vertébrés, probablement pour
    compenser la déamination spontanée des cytosines méthylées. \\
    {\em Adapté de Molecular Biology Of The Gene, Watson, 2012. } }
      \label{cytosine}
}
#+END_LaTeX
** La conversion génique biaisée vers GC

Mancera /et al/ \cite{mancera_high-resolution_2008} ont génotypé l'ensemble des
quatre haplotypes --- les tétrades --- résultants des produits de méiose de 46
levures, à haute résolution. Ils montrent qu'1% du génome de chaque produit de
méiose est soumis à de la conversion génique. Ces régions montrent une
transmission biaisée en faveur des allèles G ou C. Ils sont transmis avec une
probabilité 1.3% plus élevée qu'attendu sous l'hypothèse d'une transmission
mendélienne \cite{mancera_high-resolution_2008}. Ce biais, bien que faible, peut
affecter très fortement la probabilité de fixation des allèles GC dès lors que
la taille de la population est grande\cite{nagylaki_evolution_1983}. 

Chez la levure, le \ac{gbgc} est associé spécifiquement aux produits de
recombinaisons entraînant des crossovers \cite{lesecque_gc-biased_2013}. Il est
également associé aux évènements de conversion /simple/ --- par opposition aux
évènements complexes. Lors d'un évènement de conversion simple, le même brin est
le donneur de la conversion sur l'ensemble de la région convertie. Lors d'un
évènement complexe, les deux brins de l'hétéroduplex peuvent être donneur. 

#+BEGIN_LaTeX
\begin{transition}
  Les causes moléculaires de l'existence d'un tel mécanisme suscitent beaucoup
  d'interrogations. Différentes hypothèses ont été avancées : elles font l'objet
  de la partie suivante. 
\end{transition}
#+END_LaTeX

* Quelles hypothèses pour l'expliquer ?
Les mécanismes précis responsables du biais de conversion génique vers GC sont
encore inconnus à ce jour. Parmi les hypothèses avancées, on distinguera ici les
mécanismes moléculaires potentiellement responsables d'un tel biais, des raisons
d'être évolutives de la conversion biaisée.

*** Des propriétés inhérentes à la machinerie de réparation ?
:PROPERTIES:
:UNNUMBERED: t
:END:
\addcontentsline{toc}{subsubsection}{Des propriétés inhérentes à la réparation ?}

La machinerie de réparation pourrait présenter dans sa structure un biais en
faveur de la transmission des allèles G ou C, au cours de la conversion génique.
Chez la levure et l'Homme, la réparation des mésappariements dans les cellules
en /mitose/ est fortement biaisé vers G ou C. Les ADN glycosylases de la voie
\ac{ber} ciblent spécifiquement les bases thymines, probablement pour compenser
l'hypermutabilité des cytosines\cite{brown_specific_1987} (/cf/ Figure
\ref{cytosine}). Si la voie \ac{ber} est active au cours de la réparation des
erreurs d'appariement de la recombinaison, le biais observé pourrait être dû à
l'activité d'un mécanisme spécifiquement destiné à la réplication mitotique.

Chez la levure, l'hypothèse de l'intervention du \ac{ber} a été
exclue\cite{lesecque_gc-biased_2013}. En effet, étant donné la courte portée du
BER, les traces de conversion obtenues devraient être complexes, avec une
alternance du génotype non-biaisé et biaisé sur de courtes échelles. Pourtant,
le biais de conversion n'est observé que dans les traces simples : le brin
donneur est le même sur l'ensemble de la région convertie.

Deux modèles alternatifs ont été proposés\cite{lesecque_gc-biased_2013} : i) le
modèle de rejet de brin, et ii) le modèle du \ac{mmr} biaisé. Le modèle de rejet
de brin intervient au moment de la recherche d'homologie par le complexe
RecA-ADN simple brin : si un brin riche en AT est moins souvent rejeté que son
homologue riche en GC, la conversion a plus souvent lieu du brin riche en GC
vers le brin riche en AT. Ce qui causerait une sur-transmission de GC. 

Le modèle du \ac{mmr} biaisé dépend du choix de brin matrice pour la réparation
des mésappariements. Sur la figure \ref{mutslh}, MutH introduit une cassure sur
le brin porteur de l'allèle G. Si au contraire, la cassure est plus souvent
introduite sur les brins porteurs des allèles A ou T, G ou C est plus souvent
transmis. 

*** Un processus sélectionné pour compenser la mutation ?
:PROPERTIES:
:UNNUMBERED: t
:END:
\addcontentsline{toc}{subsubsection}{Compenser la mutation ?} 

L'intérêt évolutif d'un tel mécanisme est de second ordre : la mutation est
universellement biaisée vers AT \cite{lynch_rate_2010,hershberg_evidence_2010}.
Le \ac{gbgc} pourrait avoir été sélectionné pour contrecarrer les effets de ce
biais mutationnel \cite{marais_biased_2003, birdsell_integrating_2002}.
Autrement dit, le gBGC permettrait de /guérir/ les mutations vers AT par
recombinaison homologue. Il est également possible que le gBGC soit dû à des
mécanismes de réparation mitotiques, dont l'action biaisée vers GC est conservée
au cours de la recombinaison homologue\cite{duret_biased_2009}.
# cite birdsell

* Quelles en sont les conséquences ?

#+name: pessia
#+BEGIN_LaTeX
 \addfig{%
  \centering
  \includegraphics[width=0.7\linewidth]{img/isochores.png}
  \caption{\textbf{Les isochores : des variations de \ac{gc} à grande
      échelle.}\rmfamily \setstretch{1.1} Est représentée ici la distribution du
    taux de GC sur le chromosome humain 6. Des régions relativement homogènes en
    taux de GC se distinguent. Leur distribution est très variable sur une
    échelle de $4$Mb. Le contenu en GC est corrélé à un grand nombre d'autres
    facteurs, tels que la densité de gène, le taux de transcription ou encore la
    vitesse de réplication. \\ {\em Tiré de Eyre-Walker \& Hurst,
      2001\cite{eyre-walker_evolution_2001}} }
  \label{isochores}

  \centering
  \includegraphics[width=0.7\linewidth]{img/pessia.pdf}
  \caption{\textbf{Un gBGC universel ? Corrélation entre le taux de
      recombinaison et le contenu en GC chez les eucaryotes. } \rmfamily%
    \setstretch{1.1}%
    Parmi 36 espèces tirées des groupes eucaryotes majeurs, Pessia et
    collaborateurs ont cherché à déterminer la relation entre \ac{gc} et taux de
    recombinaison. Les \tikzcircle[PineGreen, fill=PineGreen]{3pt} et
    \tikzcircle[PineGreen, fill=White]{3pt} indiquent une corrélation positive
    entre le taux de GC et le taux de recombinaison local. Les deux
    \tikzcircle[Red, fill=Red]{3pt} indiquent les corrélations négatives
    non-compatibles avec l'hypothèses gBGC. Cette étude semble montrer
    que le gBGC est un mécanisme universel chez les eucaryotes. \\
    {\em Tiré de Pessia {\em et al.}, 2012\cite{pessia_evidence_2012}.} }
   \label{pessia}
}

#+END_LaTeX
Puisqu'elle augmente la probabilité de fixation des allèles G ou C, la
conversion biaisée joue un rôle important dans la structuration du contenu en
GC des génomes. La conversion biaisée n'est pas en soi liée à la sélection
naturelle. Elle affecte cependant la fixation d'allèles d'une façon similaire
à la sélection\cite{nagylaki_evolution_1983}. Elle a donc deux conséquences
directes et indirectes : elle interfère avec la sélection et confond les tests
de sélection naturelle.

** Il structure le contenu en GC
Les bases C et G sont liées par trois liaisons hydrogènes : elles sont plus
stables que les liaisons doubles entre A et T. Certains pensent qu'en soi, le
taux de GC est un trait adaptatif : à l'échelle du génome, un contenu en GC
supérieur en augmenterait la stabilité. Ce modèle rencontre néanmoins de
nombreuses difficultés, chez les eucaryotes comme les procaryotes. La conversion
biaisée vers GC a été proposée comme modèle alternatif expliquant les variations
en taux de GC --- \ac{gc} --- , au sein d'un génome et entre génomes.



*** Le contenu GC des génomes mammifères et la théorie des isochores
Les mammifères montrent des variations intragénomiques de grande échelle en taux
de GC\cite{eyre-walker_evolution_2001} ( $>$ 100kb ). Ces régions relativement
homogènes en taux de GC ont été baptisées /isochores/[fn:3:Voir figure
\ref{isochores}]. Leur origine fait débat : est-ce un trait sélectionné ou une
conséquence évolutive des patrons de mutations ?

Le modèle sélectionniste se heurte au fait que les variations du GC affectent
les sites fonctionnels comme neutres. En fait, l'évolution des isochores résulte
de l'accumulation de mutations. Il faudrait donc un avantage sélectif
significatif à l'acquisition d'une mutation ponctuelle vers G ou C, dans un
isochore de plus de 100kb.

Le \ac{gbgc} a été proposé pour expliquer l'apparition et le maintien des isochores
riches en GC\cite{duret_new_2006}. Un argument fort de l'hypothèse \ac{gbgc} est que
les zones fortement recombinantes ont un \ac{gc} supérieur. C'est le cas chez
l'Homme\cite{duret_impact_2008, berglund_hotspots_2009}. L'apparition et la
disparition successive de points chauds de recombinaison explique la succession
des épisodes de \ac{gbgc} : il conditionne le contenu en GC local, permettant
d'expliquer la structuration des isochores riches en GC. 

La taille des chromosomes a un impact fort sur le \ac{gc} : le taux de
recombinaison à l'échelle de la Mb est fortement corrélé à la taille du
chromosome, chez le poulet et l'Homme\cite{kaback_chromosome_1999}. Autrement
dit, les grands chromosomes recombinent peu, les petits beaucoup. Comme attendu
sous l'hypothèse \ac{gbgc}, chez l'opossum, les petits chromosomes ont un taux
de GC plus élevé que les grands.

Cette corrélation entre le taux de recombinaison et le contenu en GC local a
également été observée dans la plupart des taxons eucaryotes (voir figure
\ref{pessia}). 

#+BEGIN_LaTeX
\begin{transition}
  Ainsi, chez les mammifères, le contenu en GC est déterminé par la
  recombinaison : elle augmente la probabilité de fixation des mutations vers
  GC. Elle a pour impact de structurer localement le \ac{gc} au gré des épisodes
  de points chauds de recombinaisons. De nombreuses preuves indirectes attestent
  de l'existence du \ac{gbgc} chez les eucaryotes. Qu'en est-il chez les
  procaryotes ?
\end{transition}
#+END_LaTeX


#+name: lassalle
#+BEGIN_LaTeX
\addfig{%
  \centering
  \includegraphics[scale=1.3]{img/lassalle.png}
  \caption{\textbf{Le gBGC chez les procaryotes ? Effet de la recombinaison sur
      le contenu en GC du \emph{core genome.}} \rmfamily%
    \setstretch{1.1} %
    La différence entre le contenu en GC des gènes recombinants et des gènes
    non-recombinants est mesurée sur l'ensemble de la séquence codante
    ( \lassalleFonce ) et sur la troisième position de codon uniquement
    ( \lassalleClair ). La troisième position est moins soumise à la sélection :
    les mutations peuvent être synonymes. Le taux de GC des gènes recombinants
    est significativement supérieur à celui des non-recombinants, \emph{a fortiori}
    lorsqu'on considère les positions les moins contraintes par la sélection. \\
    {\em Tiré de Lassalle {\em et al.}, 2015 \cite{lassalle_gc-content_2015}.}
  }
  \label{lassalle}
}
#+END_LaTeX

*** Un \ac{gbgc} procaryote ?
Le taux moyen de GC chez les procaryotes est extrêmement diversifié : il varie
de 14 à 75% selon les espèces. Certains y voient une adaptation aux conditions
environnementales. En effet, la température de croissance optimale est corrélée
avec le taux de GC par exemple. Cependant, ces effets environnementaux sont
faibles, et les pressions de sélection associées mystérieuses. Le modèle
classique considère que le \ac{gc} est essentiellement déterminé par la
mutation, qui est biaisée vers
AT\cite{hershberg_evidence_2010,sueoka_directional_1988}.

Récemment, il a été démontré que les gènes recombinants ont un taux de GC
supérieur aux non-recombinants\cite{lassalle_gc-content_2015}, chez 21 espèces
bactériennes. La troisième position des codons est d'autant plus affectée
qu'elle est moins soumise à la sélection. Le code génétique étant redondant, une
mutation en troisième position ne change pas nécessairement l'acide aminé : la
mutation est synonyme. L'excès de substitutions AT $\rightarrow$ GC en troisième
position peut être dû à la pression de sélection sur les autres positions, qui
tend à conserver la fonction de la protéine. Les régions intergéniques
flanquantes des gènes recombinants ont également un \ac{gc} supérieur à celles
des régions flanquantes des gènes non-recombinants. C'est un patron attendu sous
l'hypothèse \ac{gbgc}. Cette corrélation entre taux de recombinaison et contenu
en GC est similaire quantitativement à celle observée chez
l'Humain\cite{lassalle_gc-content_2015}.

#+BEGIN_LaTeX
\begin{transition}
  Le \ac{gbgc} explique donc en partie la structuration en GC des génomes
  mammifères, eucaryotes et probablement procaryote. Il augmente la probabilité
  de fixation des allèles G ou C : il peut même s'opposer à la sélection
  naturelle si cette fixation est faiblement délétère.  
\end{transition}
#+END_LaTeX
  
#+BEGIN_LaTeX
\addfig{%
  \includegraphics[width=\linewidth]{img/pollard.png}
  \caption{\textbf{Le gBGC a-t-il interféré avec la sélection pour le
      développement des régions corticales humaines ? } \rmfamily%
    \setstretch{1.1} Pollard et collaborateurs ont analysé les régions
    non-codantes dont la vitesse d'évolution a augmenté uniquement dans la
    lignée humaine : les \ac{har}, Human Accelerated Regions. Parmi ces régions,
    la région HAR1 est particulièrement intéressante : elle comprend un gène
    codant pour un ARN régulateur exprimé au cours du développement des régions
    corticales. De façon surprenante, les 18 mutations spécifiques à l'Homme
    sont de type AT $\rightarrow$ GC (en \texttt{a}). Ces changements ont une
    influence sur la structure de l'ARN, représenté en \texttt{b} : l'hélice D
    est plus longue chez l'Homme que chez le Chimpanzé (en \texttt{c}).
    Autrement dit, le biais vers GC aurait pu influencer la divergence entre
    l'Homme et le Chimpanzé. Un ARN non-codant extrêmement conservé du Poulet au
    Chimpanzé a brutalement accéléré dans la lignée humaine. La sélection et le
    gBGC ont pu agir de concert pour altérer la structure de cet ARN. \\ {\em
      Adapté de Pollard {\em et al.}, 2006 \cite{pollard_rna_2006}.} }
  \label{pollard}
}

#+END_LaTeX

** Il interfère avec la sélection 
La conversion génique affecte la probabilité de fixation d'un allèle de façon
similaire à la sélection \cite{nagylaki_evolution_1983}. Si un allèle faiblement
délétère est porté par une substitution AT $\rightarrow$ GC, le \ac{gbgc} peut
entraîner sa fixation dans la population. À l'inverse, il peut empêcher la
fixation d'une mutation GC $\rightarrow$ AT. Il contrecarre les effets de la
sélection naturelle.

Galtier et collaborateurs ont analysé la séquence des protéines de primates qui
montrent un taux d'évolution plus rapide depuis la divergence avec les macaques
\cite{galtier_gc-biased_2009}. Cette accélération de la vitesse de substitution
dans les séquences codantes peut /a priori/ être due à un changement de fonction
/adaptatif/. Cependant, les séquences analysées montrent un excès significatif
de mutations AT $\rightarrow$ GC. De plus, ces mutations sont significativement
plus souvent non-synonymes : elles changent l'acide aminé. En clair, des régions
auparavant conservées ont subie un ou plusieurs épisodes de gBGC, qui ont
entraîné deux choses : i) le \ac{gc} local a augmenté, et ii) la fonction des
régions a changé (\emph{cf} Figure \ref{pollard}).

** Il confond les tests de sélection 
Les tests de sélection reposent classiquement sur deux principes généraux
\cite{hurst_genetics_2009} : ce qui évolue lentement est fonctionnel, ce qui
évolue vite est adaptatif. L'approche privilégiée pour détecter les régions
influencées par la sélection est de comparer les génomes, puis d'identifier les
régions qui évoluent rapidement, sur une branche particulière de l'arbre
phylogénétique obtenu\cite{ratnakumar_detecting_2010}.

Le gBGC a cependant une empreinte sur les séquences similaire à celle de la
sélection dirigée : il peut brouiller les tests de sélection. L'action de la
sélection naturelle est alors confondue avec celle d'un processus neutre voir
mal-adaptatif. Typiquement, le ratio $\nicefrac{d_N}{d_S}$, qui résume le
rapport entre le taux de mutations non-synonymes $d_N$ et synonymes $d_S$, est
supérieur à 1 lorsque la protéine est sous sélection positive, en faveur du
changement de fonction. Ratnakumar et collaborateurs ont estimé qu'environ 20%
des régions avec un ratio $\nicefrac{d_N}{d_S}$ élevé pourraient avoir été sous
l'influence du gBGC. 

Le gBGC brouille les traces de la sélection naturelle.  
* Conclusion
:PROPERTIES:
:UNNUMBERED: t
:END:

La conversion génique biaisée vers GC est un mécanisme potentiellement
universel, qui affecte localement le taux de GC des régions recombinantes. Bien
que généralement faible, le biais peut avoir un impact fort sur la fixation d'un
allèle, si la taille efficace de la population est grande. Il contribue à
structurer le taux de GC des génomes, peut contrecarrer la sélection, et pose
des problèmes de détection de celle-ci. De nombreuses interrogations restent en
suspens. Les mécanismes qui le sous-tendent sont encore mystérieux, de même que
sa raison d'être évolutive. L'extension récente de l'hypothèse gBGC aux
procaryotes reste à confirmer expérimentalement. Elle constitue néanmoins un
terrain d'exploration nouveau, qui pourrait permettre d'étudier plus avant la
machinerie moléculaire responsable d'un phénomène /a priori/ anodin, mais dont
les conséquences sont nombreuses. 

\input{endmatter.tex}
